### ISSUE TITLE
Vpopmail versions including several patches

### ISSUE THREAD

**Issue by brunonymous** [semhoun/sqmail_all-in-one#11]
For your information, we have a version of Vpopmail with several patches. Patches from Roberto, FreeBSD, Gentoo and other patches. Perhaps you will be interested in this version:
 https://github.com/brunonymous/vpopmail
The list of changes can be consulted here:
https://github.com/brunonymous/vpopmail/blob/main/ChangeLog

**Comment by semhoun** [comment]
It seem very promising. I will try it.

**Comment by semhoun** [comment]
Added some patch, and use it as replacement for current vpopmail
